import "dotenv/config";
import mysql from "mysql2/promise";

const { MYSQL_DB_HOST, MYSQL_DB_USER, MYSQL_DB_PASSWORD, MYSQL_DB_NAME } =
  process.env;

const seedData = [
  {
    nom: "René Dupont",
    age: 45,
    profession: "Fonctionnaire du Ministère de la Vérité",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-483920",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen1.png",
    notes: "Regard vide, répond lentement.",
    valide: 1,
  },
  {
    nom: "Claire Moreau",
    age: 31,
    profession: "Technicienne de propagande",
    origine: "Eurasia",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "EU-192820",
    slogan: "La liberté, c’est l’esclavage",
    image: "/faces/citoyen2.png",
    notes: "Accent suspect.",
    valide: 0,
  },
  {
    nom: "Louis Garnier",
    age: 29,
    profession: "Ouvrier",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 0,
    numeroPasseport: "",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen3.png",
    notes: "Semble pressé.",
    valide: 0,
  },
  {
    nom: "Sophie Lemoine",
    age: 37,
    profession: "Archiviste au Ministère de l'Amour",
    origine: "Océania",
    affiliation: "Parti intérieur",
    passeport: 1,
    numeroPasseport: "OC-729384",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen4.png",
    notes: "Très froide, peu expressive.",
    valide: 1,
  },
  {
    nom: "Julien Bernard",
    age: 54,
    profession: "Retraité",
    origine: "Estasia",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "ES-129384",
    slogan: "La paix, c’est la guerre",
    image: "/faces/citoyen5.png",
    notes: "Confus sur sa destination.",
    valide: 0,
  },
  {
    nom: "Nathalie Roux",
    age: 40,
    profession: "Secrétaire de cellule",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-847192",
    slogan: "La liberté, c’est l’esclavage",
    image: "/faces/citoyen6.png",
    notes: "Réponds avec fierté au slogan.",
    valide: 1,
  },
  {
    nom: "Thierry Dumas",
    age: 28,
    profession: "Ouvrier",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-000321",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen7.png",
    notes: "Portait une affiche interdite.",
    valide: 0,
  },
  {
    nom: "Isabelle Fontaine",
    age: 26,
    profession: "Chanteuse approuvée",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-282019",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen8.png",
    notes: "Chante l’hymne avec ferveur.",
    valide: 1,
  },
  {
    nom: "Marc Lefèvre",
    age: 34,
    profession: "Imprimeur",
    origine: "Eurasia",
    affiliation: "Prolétaire",
    passeport: 0,
    numeroPasseport: "",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen9.png",
    notes: "Hésitant sur ses papiers.",
    valide: 0,
  },
  {
    nom: "Élise Petit",
    age: 33,
    profession: "Fonctionnaire du Ministère de la Paix",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-938201",
    slogan: "La liberté, c’est l’esclavage",
    image: "/faces/citoyen10.png",
    notes: "Dossier impeccable.",
    valide: 1,
  },
  {
    nom: "Luc Martin",
    age: 36,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100011",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen11.png",
    notes: "A récité les slogans du Parti sans hésitation, posture rigide.",
    valide: 1,
  },
  {
    nom: "Camille Dubois",
    age: 37,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100012",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen12.png",
    notes: "A évité le contact visuel, semble nerveux à l'évocation du Parti.",
    valide: 0,
  },
  {
    nom: "Pierre Lemoine",
    age: 38,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100013",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen13.png",
    notes:
      "S’est exprimé avec discipline, connaît bien les directives du Parti.",
    valide: 1,
  },
  {
    nom: "Sophie Robert",
    age: 39,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100014",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen14.png",
    notes: "Doute sur la date de sa dernière révision idéologique.",
    valide: 1,
  },
  {
    nom: "Antoine Morel",
    age: 40,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Prolétaire",
    passeport: 0,
    numeroPasseport: "",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen15.png",
    notes:
      "Répond lentement aux questions, évite de parler de sa région d'origine.",
    valide: 1,
  },
  {
    nom: "Julie Marchand",
    age: 41,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100016",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen16.png",
    notes: "Comportement exemplaire, uniforme impeccable.",
    valide: 0,
  },
  {
    nom: "Damien Chevalier",
    age: 42,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100017",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen17.png",
    notes: "Porte le pin’s du Parti sur la poitrine, visage inexpressif.",
    valide: 1,
  },
  {
    nom: "Hélène Durand",
    age: 43,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100018",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen18.png",
    notes: "Répète souvent les slogans comme une prière, regard inquiet.",
    valide: 1,
  },
  {
    nom: "François Giraud",
    age: 44,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100019",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen19.png",
    notes: "Répond correctement à toutes les vérifications de loyauté.",
    valide: 1,
  },
  {
    nom: "Marine Picard",
    age: 45,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 0,
    numeroPasseport: "",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen20.png",
    notes: "Oublie ses papiers, justifie par une urgence familiale floue.",
    valide: 0,
  },
  {
    nom: "Alain Renault",
    age: 46,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100021",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen21.png",
    notes: "Parle avec conviction, cite des discours du Parti par cœur.",
    valide: 1,
  },
  {
    nom: "Claire Noël",
    age: 47,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100022",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen22.png",
    notes: "Se présente en avance, dossiers soigneusement organisés.",
    valide: 1,
  },
  {
    nom: "Michel Benoît",
    age: 48,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100023",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen23.png",
    notes: "Répète souvent “je suis un bon citoyen”, anxieux.",
    valide: 1,
  },
  {
    nom: "Laura Caron",
    age: 49,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100024",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen24.png",
    notes: "Odeur forte d’huile de machine, parle très peu.",
    valide: 0,
  },
  {
    nom: "André Leclerc",
    age: 50,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 0,
    numeroPasseport: "",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen25.png",
    notes: "Cherche à éviter certaines questions sur son passé.",
    valide: 1,
  },
  {
    nom: "Chloé Perrot",
    age: 51,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100026",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen26.png",
    notes: "Confiant, récite les dates clés du Parti sans erreur.",
    valide: 1,
  },
  {
    nom: "Jean Millet",
    age: 52,
    profession: "Travailleur d'État",
    origine: "Eurasia",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100027",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen27.png",
    notes: "Vêtu de manière négligée, connaît toutefois les slogans.",
    valide: 1,
  },
  {
    nom: "Émilie Faure",
    age: 53,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Parti extérieur",
    passeport: 1,
    numeroPasseport: "OC-100028",
    slogan: "La guerre, c’est la paix",
    image: "/faces/citoyen28.png",
    notes: "Calme, parle avec des phrases toutes faites apprises par cœur.",
    valide: 0,
  },
  {
    nom: "Patrick Barbier",
    age: 54,
    profession: "Travailleur d'État",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-100029",
    slogan: "Ignorance, c’est la force",
    image: "/faces/citoyen29.png",
    notes: "Cherchait à cacher un document froissé dans sa poche.",
    valide: 1,
  },
  {
    nom: "Hugo Delattre",
    age: 39,
    profession: "Ouvrier textile",
    origine: "Océania",
    affiliation: "Prolétaire",
    passeport: 1,
    numeroPasseport: "OC-002938",
    slogan: "Ignorance, c’est la force",
    image: "/faces/30.png",
    notes: "Comportement exemplaire, uniforme impeccable.",
    valide: 0,
  },
];

const seed = async () => {
  try {
    const db = await mysql.createConnection({
      host: MYSQL_DB_HOST,
      user: MYSQL_DB_USER,
      password: MYSQL_DB_PASSWORD,
      database: MYSQL_DB_NAME,
    });

    await db.query("DELETE FROM citoyens");

    for (const {
      nom,
      age,
      profession,
      origine,
      affiliation,
      passeport,
      numeroPasseport,
      slogan,
      image,
      notes,
      valide,
    } of seedData) {
      await db.query(
        "INSERT INTO citoyens (nom, age, profession, origine, affiliation, passeport, numeroPasseport, slogan, image, notes, valide) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
          nom,
          age,
          profession,
          origine,
          affiliation,
          passeport,
          numeroPasseport,
          slogan,
          image,
          notes,
          valide,
        ]
      );
    }

    await db.end();
    console.log("🌱 Database seeded successfully");
  } catch (err) {
    console.error("❌ Error during seeding:", err);
  }
};

seed();
